# Generated by Django 5.2.1 on 2025-06-30 09:42

import detector.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chickenanalysis',
            options={'ordering': ['-analysis_date'], 'verbose_name': 'Chicken Analysis', 'verbose_name_plural': 'Chicken Analyses'},
        ),
        migrations.AlterField(
            model_name='chickenanalysis',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the analysis was performed'),
        ),
        migrations.AlterField(
            model_name='chickenanalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence score as percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='chickenanalysis',
            name='image',
            field=models.ImageField(help_text='Upload an image of chicken droppings for analysis', upload_to=detector.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='chickenanalysis',
            name='predicted_disease',
            field=models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Coccidiosis', 'Coccidiosis'), ('Salmonella', 'Salmonella'), ('Newcastle Disease', 'Newcastle Disease')], help_text='Predicted disease from ML analysis', max_length=100),
        ),
        migrations.AddIndex(
            model_name='chickenanalysis',
            index=models.Index(fields=['-analysis_date'], name='detector_ch_analysi_6df879_idx'),
        ),
        migrations.AddIndex(
            model_name='chickenanalysis',
            index=models.Index(fields=['predicted_disease'], name='detector_ch_predict_9ebdf0_idx'),
        ),
    ]
