steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/disease-detection:latest'
      - '.'
      - '--build-arg'
      - 'MODEL_GDRIVE_ID=${_MODEL_GDRIVE_ID}'
    dir: 'disease_detection'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/disease-detection:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'disease-detection'
      - '--image'
      - 'gcr.io/$PROJECT_ID/disease-detection:latest'
      - '--region'
      - 'us-central1'  # Choose your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GS_BUCKET_NAME=${_GS_BUCKET_NAME},GS_PROJECT_ID=${PROJECT_ID},DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY},DEBUG=False'

images:
  - 'gcr.io/$PROJECT_ID/disease-detection:latest'
