# Generated by Django 5.2.3 on 2025-06-29 17:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='chicken_images/')),
                ('predicted_disease', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
